name: TempBanUI
main: SonsaYT\TempBanUI\Main
api: [3.0.5]
version: 1.5
author: SonsaYT

commands:
 tban:
  description: "Open TempBanUI"
  permission: use.tban
  
 tcheck:
  description: "Check ban list"
  permission: use.tcheck
