name: TempBanUI
main: TempBanUI\Main
api: [3.0.0-ALPHA12]
version: 1.3
author: SonsaYT

commands:
 tban:
  description: "Open TempBanUI"
  permission: use.tban
  
 tcheck:
  description: "Check ban list"
  permission: use.tcheck
